### ISSUE TITLE
SVG format icon request

### ISSUE THREAD

**Issue by ghost** [PapirusDevelopmentTeam/papirus-libreoffice-theme#11]
@SmartFinn ,@varlesh
I need some of papirus-libreoffice-theme icons in SVG format to use for [papirus-calibre-theme](https://github.com/PapirusDevelopmentTeam/papirus-calibre-theme), mainly for editing icons which are used in calibre book edit and metadate edit. can I have them?

**Comment by SmartFinn** [comment]
As far as I know,  papirus-libreoffice-theme based on sifr, so SVG files can be found here https://github.com/libodesign/icons

But I don't understand why need to use monochrome icons in color theme :confused:

**Comment by SmartFinn** [comment]
@morealaz create an issue that contains icons that you can not find/draw, and we will draw them :wink:

**Comment by ghost** [comment]
I just create a [ToDo List](https://github.com/PapirusDevelopmentTeam/papirus-calibre-theme/issues/3) please see it and feel free to create icons which are not already in papirus.
