### ISSUE TITLE
Colors for new Papirus

### ISSUE THREAD

**Issue by varlesh** [PapirusDevelopmentTeam/papirus-libreoffice-theme#4]
papirus now have another colors and will be good if we change this colors for LO themes too...

**Comment by varlesh** [comment]
@SmartFinn Серёж, извини что достал тебя уже... но ты у нас самый мозговитый парень. В общем как ты знаешь, мы поеняли с тобой цвет actions на #d3dae3 для Dark и #5c616c для Light. Может есть какой-то способ, что бы пофиксить текущте значки для LO? Потому как они сейчас вообще черные с прозрачностью 50% и 72% (как в предыдущем варианте Papirus)

**Comment by varlesh** [comment]
Есть другой вариант, более сложный... Это взять исходник Sifr icon theme (https://github.com/LibreOffice/core/tree/master/icon-themes/sifr) и адаптировать его под Papirus

**Comment by SmartFinn** [comment]
@varlesh а SVG исходников не было, или не осталось? Для png можно попробовать чем-то пакетным поменять яркость-контрастность.

**Comment by varlesh** [comment]
SVG нет у них изначально, тоже самое кстати и с темой для SMPlayer (правда эту тему делал я сам, но вот не хватило ума сохранить исходники в SVG).
Есть ли какой-то способ убрать прозрачность, а потом применить тонирование в нужный цвет пакетным вариантом?

**Comment by SmartFinn** [comment]
imagemagick думаю есть смысл колупать, опций там завались.

**Comment by varlesh** [comment]
Сейчас качаю иходник LO, гляну что там в Sifr... может проще будет просто адаптировать

**Comment by varlesh** [comment]
А вот с SMPlayer походу придется колупаться :(

**Comment by SmartFinn** [comment]
С прозрачностью вряд ли получится, всю сглаженность испортит.

**Comment by varlesh** [comment]
Да, наверное придется заново все делать

**Comment by SmartFinn** [comment]
Ага, с яркостью-контрастность тоже не получилось бы, как никрути но с `#737373` `#5c616c` не получишь.
