### ISSUE TITLE
installed but not included in libre office Version: 5.4.0.3 icon style selection

### ISSUE THREAD

**Issue by artkis** [PapirusDevelopmentTeam/papirus-libreoffice-theme#7]

**Comment by SmartFinn** [comment]
Distro?
What method do you use to install LibreOffice 5.4? Flatpak?

**Comment by SmartFinn** [comment]
Added support for official fresh builds https://www.libreoffice.org/download/download/

Now you can install it via [Papirus installer](https://github.com/PapirusDevelopmentTeam/papirus-libreoffice-theme#papirus-installer) using the command:

```
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-libreoffice-theme/master/install-papirus-root.sh | sh
```

or using make:

```
sudo make install PREFIX="/opt" NAME="libreoffice5.4"
```

Installing via deb packages are not supported.

**Comment by artkis** [comment]
Sorry for the late reply.
After for today's software update.
the icon problem was fixed.
It is not flatpak, 
Thanks a lot SmartFinn
